[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[project]
name = "rebuildap"
version = "0.0.1"
authors = [
  { name="Bernhard Wagner", email="rebuildap@nosuch.biz" },
]
description = "rebuild Audacity project"
readme = "README.md"
license = { file = "LICENSE.txt"}
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "pyperclip",
    "psutil",
    "typer",
    "pyaudacity @ git+https://github.com/bwagner/pyaudacity.git",
]

[dependency-groups]
dev = [
    "pytest>=7.4.4",
]

[project.urls]
"Homepage" = "https://github.com/bwagner/rebuildap"
"Bug Tracker" = "https://github.com/bwagner/rebuildap/issues"

[tool.uv.build-backend]
module-root = ""

[tool.ruff.lint]
extend-select = ["I"]

[project.scripts]
rebuildap = "rebuildap:main"

[tool.pytest.ini_options]
addopts = "--doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE ELLIPSIS"
testpaths = [
    "tests",
]
